name: semseg
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    #- python==3.5.2
    - numpy
    - matplotlib
    - jupyter
    - opencv3
    # - scikit-learn
    # - scikit-image
    - scipy
    - pandas
    #- ffmpeg
    - tqdm
    - pip:
        - tensorflow-gpu
        - keras